version: '3.1'

services:

  mongo:
    container_name: postgres-dev
    image: 13.3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stripe-example
